# Project: sort_str
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = sort_str.o
LINKOBJ  = sort_str.o
LIBS     = -L"F:/Tools/DevCppPortable/MinGW64/lib" -L"F:/Tools/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Tools/DevCppPortable/MinGW64/include" -I"F:/Tools/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"F:/Tools/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Tools/DevCppPortable/MinGW64/include" -I"F:/Tools/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"F:/Tools/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Tools/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = sort_str.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

sort_str.o: sort_str.c
	$(CC) -c sort_str.c -o sort_str.o $(CFLAGS)
